setup.sh

Add poetry env use python3.11 to setup

fix setup remove_poetry_env

---

README.md
setup.sh

- Update set up script
- Stuff

Update set up script

---

.env.example
README.md
scripts/tracking.py
setup.sh
skyvern/config.py

Update setup.sh to ask for openai key and email

---

setup.sh

- deactivate poetry env before cleaning it up
- fail the script if python 3.11 isn't installed

Choose poetry env python version earlier

---

setup.sh

https://github.com/Skyvern-AI/skyvern/issues/85 
https://github.com/Skyvern-AI/skyvern/issues/41
https://github.com/Skyvern-AI/skyvern/issues/36

Upgrade setup.sh to include docker postgres

---

.github/workflows/ci.yml
.gitignore
skyvern-frontend/.eslintrc
skyvern-frontend/.husky/pre-commit
skyvern-frontend/.prettierignore
skyvern-frontend/README.md
skyvern-frontend/index.html
skyvern-frontend/package-lock.json
skyvern-frontend/package.json
skyvern-frontend/src/App.tsx
skyvern-frontend/src/main.tsx
skyvern-frontend/src/vite-env.d.ts
skyvern-frontend/tsconfig.json
skyvern-frontend/tsconfig.node.json
skyvern-frontend/vite.config.ts

- Create app with `vite create`
- Configure ESLint, Typescript
- Configure husky for pre-commit actions
- Configure github workflow for frontend

Initialize frontend app

---

setup.sh

fix https://github.com/Skyvern-AI/skyvern/issues/108

fix wrong host in setup

---

poetry.lock
pyproject.toml
skyvern/forge/sdk/db/client.py
skyvern/forge/sdk/db/models.py

This PR migrates all the synchronous sqlalchemy pattern to async pattern

Sqlalchemy AsyncSession

---

.pre-commit-config.yaml
skyvern/forge/sdk/db/client.py
skyvern/forge/sdk/routes/agent_protocol.py
skyvern/forge/sdk/workflow/context_manager.py
skyvern/forge/sdk/workflow/exceptions.py
skyvern/forge/sdk/workflow/models/block.py
skyvern/forge/sdk/workflow/models/yaml.py
skyvern/forge/sdk/workflow/service.py

Workflow: YAML interface

---

poetry.lock

https://github.com/Skyvern-AI/skyvern/issues/118

Upgrade litellm version to 1.34.8

---

streamlit_app/visualizer/streamlit.py

Improve visualizer output when invalid auth token is provided

---

skyvern/exceptions.py
skyvern/forge/prompts/skyvern/extract-action.j2
skyvern/webeye/actions/handler.py

- support setup in action 
- support teardown in action

add action setup/teardown stage

---

skyvern/forge/agent.py
skyvern/forge/sdk/workflow/models/block.py
skyvern/webeye/actions/handler.py
skyvern/webeye/scraper/domUtils.js

Reverts Skyvern-AI/skyvern#181

Revert "Don't interact with fields that are already filled in"

---

poetry.lock
skyvern-frontend/src/routes/tasks/create/CreateNewTaskForm.tsx
skyvern/forge/sdk/api/llm/models.py

https://litellm.vercel.app/docs/routing#advanced---routing-strategies

New LLM Router strategy

---

skyvern/webeye/scraper/domUtils.js

- open the dropdown before scraping so we can get the options in the scraped_page.
- send the option value to LLM, helping it to make the right choice.

support dropdown on combobox

---

skyvern/forge/agent.py
skyvern/forge/sdk/api/aws.py
skyvern/forge/sdk/db/client.py
skyvern/forge/sdk/workflow/models/block.py
skyvern/forge/sdk/workflow/service.py
skyvern/webeye/actions/handler.py
skyvern/webeye/browser_factory.py
skyvern/webeye/scraper/scraper.py

log exception has `exc_info=True` [by default](https://medium.com/@rahulkumar_33287/logger-error-versus-logger-exception-4113b39beb4b)

remove exc_info from LOG.exception

---

skyvern/config.py
skyvern/webeye/browser_factory.py

- most proxies are slow but not bad. Therefore we should increase the initial loading to from 30s to 2mins

fix backbone connection

---

skyvern-frontend/src/routes/root/RootLayout.tsx

Default to dark theme for now

---

skyvern/webeye/browser_factory.py

Update screenshot logic

---

docs/quickstart.mdx

docs: update quickstart.mdx

---

skyvern-frontend/src/components/ui/card.tsx
skyvern-frontend/src/components/ui/dropdown-menu.tsx
skyvern-frontend/src/routes/tasks/running/QueuedTasks.tsx
skyvern-frontend/src/routes/tasks/running/RunningTasks.tsx

- Change card header background
- Change dropdown menu cursor
- Remove unnecessary computation in queued and running tasks

UI improvements

---

skyvern/forge/agent.py
skyvern/forge/sdk/api/aws.py
skyvern/forge/sdk/artifact/manager.py
skyvern/forge/sdk/artifact/storage/base.py
skyvern/forge/sdk/artifact/storage/local.py
skyvern/forge/sdk/routes/agent_protocol.py
skyvern/forge/sdk/workflow/service.py

to avoid initializing a connection for each presigned url

Implement get_share_links

---

README.md

Updating based on feedback to prioritize dockercompose setup

Update README prioritizing docker instructions

---

skyvern/webeye/actions/handler.py

- support select action on <label> of <input>(checkbox/radio)
- use check to avoid double clicks, which will uncheck the checkbox

optimize select action

---

skyvern/forge/sdk/routes/agent_protocol.py
skyvern/forge/sdk/workflow/models/workflow.py
skyvern/forge/sdk/workflow/service.py

Update workflow response and webhook, bugfix: workflow is always completed

---

setup.sh
skyvern/forge/sdk/api/llm/config_registry.py

gpt-4o integration

---

skyvern/forge/sdk/api/llm/utils.py

Auto-fix invalid JSON

---

skyvern-frontend/src/routes/tasks/create/CreateNewTaskFormPage.tsx
skyvern-frontend/src/routes/tasks/create/SavedTaskForm.tsx

Disable refetch on window focus for saved task form

Fix a bug caused by setting staleTime to zero

---

skyvern-frontend/src/util/env.ts

Let's not put errors in console for values that are optional

Turn environment variable errors to warnings

---

skyvern-frontend/src/api/types.ts

add extract action type in frontend

---

fern/fern.config.json

This PR upgrades fern and gets fern check working on your repo!

chore: upgrade fern to `0.56.29`

---

skyvern/forge/sdk/workflow/models/block.py

Reverts Skyvern-AI/skyvern#2114

Revert "set task_id in skyvern_context when task block starts"

---

fern/openapi/skyvern_openapi.json

Update API specifications by running fern api update.
---
🔄 This PR updates API specifications by running the `fern api update` command to synchronize the project's API definitions with the latest schema changes. The update ensures that the API documentation and generated code remain consistent with current specifications.
<details>
<summary>🔍 <strong>Detailed Analysis</strong></summary>
- **API Specification Update**: Automated update of API specifications using Fern's tooling
- **Schema Synchronization**: Ensures API definitions are aligned with the latest schema requirements
- **Documentation Refresh**: Updates generated API documentation to reflect current specifications
```mermaid
flowchart TD
A[Fern API Update Command] --> B[Schema Validation]
B --> C[Specification Files Updated]
C …
```

Update API specifications with fern api update
